### PR TITLE
Daily branch rebase

### PR DESCRIPTION
**Pull request by guogan1234**
Rebase daily_branch and resolve conflicts between main branch and daily_branch.

### CODE REVIEW

**Review by a-molis — CHANGES_REQUESTED** [review]

**Review by smiller1212 — COMMENTED** [review]
I don't see changes to the CMakeLists.txt file, which should include the media_data_box and time_to_sample_box in it. Make sure the project can build properly, and that the test-app at least can run. If you confirm that that happens, then I think it is ok to merge and I will approve the changes.

**Comment by guogan1234** [comment]
> I don't see changes to the CMakeLists.txt file, which should include the media_data_box and time_to_sample_box in it. Make sure the project can build properly, and that the test-app at least can run. If you confirm that that happens, then I think it is ok to merge and I will approve the changes.

I forgot to change thr CMakeList.txt file. And it has some issues yesterday. However, it can build and the test-app works successful in my local machine today.

**Review by a-molis — APPROVED** [review]
This looks good to me

**Review by smiller1212 — APPROVED** [review]
PR looks good

**Pull request merged**
