### PR TITLE
add the classes for mdat and stts

### PR DESCRIPTION
**Pull request by guogan1234**

### CODE REVIEW

**Comment by smiller1212** [comment]
Make sure you only commit changes that do not already exist on the main branch. It looks like you already branched off main before we pushed the initial changes, so you also include those same initial changes in your code. 

So if you don't mind, go through and remove the changes that are already reflected in main, likely the include/lovok.h, src/box.h, and src/file_type_box.h parts of your branch are already there, so they don't need to be merged again

**Review by smiller1212 — CHANGES_REQUESTED** [review]
Make sure you only commit changes that do not already exist on the main branch. It looks like you already branched off main before we pushed the initial changes, so you also include those same initial changes in your code.

So if you don't mind, go through and remove the changes that are already reflected in main, likely the include/lovok.h, src/box.h, and src/file_type_box.h parts of your branch are already there, so they don't need to be merged again

**Comment by guogan1234** [comment]
> 
I didn't change the lovok.h and the file_type_box.h. I only change the box.h file.
In my opinion, I add a constructor which takes an arguement in the box.h. I think we need it because a lot of box need to construct a box instance with a specific boxtype. Thus, I think we need to provide a box(std::string) constructor in the box.h.

**Comment by smiller1212** [comment]
That is fine, but the other files which you did not chance (ie. src/file_type_box.h src, include/lovok.h) should not be included in the merge request. If you don't mind removing these files to avoid merge conflicts, then fixing the existing merge conflicts, then I can approve and merge your PR

**Comment by guogan1234** [comment]
> That is fine, but the other files which you did not change (ie. src/file_type_box.h src, include/lovok.h) should not be included in the merge request. If you don't mind removing these files to avoid merge conflicts, then fixing the existing merge conflicts, then I can approve and merge your PR

Thanks, Samuel. I have removed the files that are already existed. Thus, you can review them again.

**Pull request closed without merging**
